version: "3.9"
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379"
    environment:
      GET_HOSTS_FROM: dns
    restart: on-failure
    volumes:
      - cache_data:/data
  backend-api:
    image: laerson/ghrepos-api:latest  
    environment:
      JAVA_OPTS: "-Ddebug=false -Dspring.profiles.active=default -Dspring.cache.type=redis -Dspring.redis.host=redis -Dspring.redis.port=6379"
      GET_HOSTS_FROM: dns
    depends_on:
      - redis
    ports:
      - "8080-8084"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 90s
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  loadbalancer:
    image: nginx
    volumes:
      - ./data/loadbalancer:/etc/nginx/templates
    ports:
      - "80:80"
    environment:
      GET_HOSTS_FROM: dns
      NGINX_PORT: 80
    restart: on-failure
volumes:
  cache_data: 